### ISSUE TITLE
no initialization when tests='all'

### ISSUE THREAD

**Issue by ch-shin** [snorkel-ai/long-context-eval#2]
https://github.com/snorkel-ai/long-context-eval/blob/0a09f4fd999216d4e3696123f5e4b573017574d3/long_context_eval/evals/single_hop_qa.py#L104

```

>>>>Generate llm responses w/ long context and RAG at noise levels [0, 5, 11, 17, 23]...
# of noisy documents:  0
  0%|                                                                                                                                                            | 0/20 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/Users/chshin/long-context-eval/long_context_eval/run_benchmark.py", line 65, in <module>
    main()
  File "/Users/chshin/long-context-eval/long_context_eval/run_benchmark.py", line 49, in main
    lctest.test_long_context_length_versus_rag()
  File "/Users/chshin/long-context-eval/long_context_eval/evals/single_hop_qa.py", line 635, in test_long_context_length_versus_rag
    vectorstore = Chroma.from_documents(documents=splits, embedding=self.embedding_model.model)
                                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SingleHopQATest' object has no attribute 'embedding_model'

``

**Comment by amy12xx** [comment]
This is fixed in the latest commit https://github.com/snorkel-ai/long-context-eval/commit/7e569c66d244b84b3addf53a872394c87649967c
